### ISSUE TITLE
index e home

### ISSUE THREAD

**Issue by luciostuder** [lucasrmartins0/lucasrmartins0.github.io#1]
- na pasta lab2, deve apenas haver index.html. O home é o index.
- Põe o texto em português.
- depois do elemento `header` começas logo com um `h2` em todas as paginas. deves usar elementos semanticos `main` e `footer`!
- no report.html, a referencia às imagens está errada! retira a barra "/", pois indica erradamente para ir para a pasta "mãe". E nunca uses em nomes de ficheiros espaços ou carateres especiais como "ç" ou ã"

**Comment by lucasrmartins0** [comment]
Boa tarde professor, obrigado pelo feedback!
Já alterei e submeti no moodle!
Cumprimentos, Lucas Martins
